services:

  # postgres:
  #   image: 'postgres:17.0-alpine3.20'
  #   environment: # NOTE: Must declare in the ENV file
  #     - 'POSTGRES_DB=goutapp'
  #     - 'POSTGRES_USER=goutsvc'
  #     - 'POSTGRES_PASS WORD=secret'
  #   ports:
  #     - '5432:5432'
  lgtm:
    image: grafana/otel-lgtm
    container_name: gout-backend-lgtm
    ports:
      - '4317:4317'
      - '4318:4318'
      - '3000:3000'
#  gout:
#    image: 'korn704/gout-lgtm:latest'
#    ports:
#      - '8080:8080'
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gout
#      SPRING_DATASOURCE_USERNAME: gout
#      SPRING_DATASOURCE_PASSWORD: secret
