server:
  shutdown: graceful

spring:
  application:
    name: "Gout Together"
  docker:
    compose:
      enabled: true
  threads:
    virtual:
      enabled: true
  mvc:
    problemdetails:
      enabled: true
  # DB Connection - PostgreSQL
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/gout}
    username: ${DATABASE_USER:goutapp}
    password: ${DATABASE_PASSWORD:secret}
    hikari:
      maximum-pool-size: ${POOL_SIZE:10}
  # DB Migration
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: ${IS_FLYWAY_BASELINE_ON_MIGRATE:true}
    validate-on-migrate: ${IS_FLYWAY_VALIDATE_ON_MIGRATE:true}
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"

oauth:
  private-key: ${OAUTH_PRIVATE_KEY_BASE64:DUMMY}
  public-key: ${OAUTH_PUBLIC_KEY_BASE64:DUMMY}

org.jobrunr:
  background-job-server:
    enabled: ${JOBRUNR_BACKGROUND_JOB_ENABLED:true}
    thread-type: VirtualThreads
  dashboard:
    enabled: ${JOBRUNR_DASHBOARD_ENABLED:true}


goutapp:
  booking:
    tour-price: 100.00
  token:
    access-token-expired-in-seconds: ${ACCESS_TOKEN_EXP_SEC:3600} # Default: 1 hour
    refresh-token-expired-in-seconds: ${REFRESH_TOKEN_EXP_SEC:2592000} # Default: 1 month
